/* AUTH ACTIONS */
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERROR = 'CLEAR_ERROR';

/* FAVORITE ARTIST ACTIONS */
export const FETCH_ARTISTS_REQUEST = 'FETCH_ARTISTS_REQUEST';
export const FETCH_ARTISTS_SUCCESS = 'FETCH_ARTISTS_SUCCESS';
export const FETCH_ARTISTS_FAILED = 'FETCH_ARTISTS_FAILED';
export const SELECT_FAVORITE_ARTIST = 'SELECT_FAVORITE_ARTIST';
export const DESELECT_FAVORITE_ARTIST = 'DESELECT_FAVORITE_ARTIST';
export const SAVE_ARTISTS_REQUEST = 'SAVE_ARTISTS_REQUEST';
export const SAVE_ARTISTS_SUCCESS = 'SAVE_ARTISTS_SUCCESS';
export const SAVE_ARTISTS_FAILED = 'SAVE_ARTISTS_FAILED';

/* WAITING ACTIONS */
export const CREATE_GAME_REQUEST = 'CREATE_GAME_REQUEST';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_FAILED = 'CREATE_GAME_FAILED';
export const FETCH_GAMES_REQUEST = 'FETCH_GAMES_REQUEST';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE';
export const ENTER_GAME_REQUEST = 'ENTER_GAME_REQUEST';
export const ENTER_GAME_SUCCESS = 'ENTER_GAME_SUCCESS';
export const ENTER_GAME_FAILED = 'ENTER_GAME_FAILED';

