/* AUTH ACTIONS */
export const REQUEST_SIGNUP_START = 'REQUEST_SIGNUP_START';
export const REQUEST_SIGNUP_SUCCESS = 'REQUEST_SIGNUP_SUCCESS';
export const REQUEST_SIGNUP_FAILURE = 'REQUEST_SIGNUP_FAILURE';
export const REQUEST_LOGIN_START = 'REQUEST_LOGIN_START';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILURE = 'REQUEST_LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERROR = 'CLEAR_ERROR';

/* FAVORITE ARTIST ACTIONS */
export const FETCH_ARTISTS_START = 'FETCH_ARTISTS_START';
export const FETCH_ARTISTS_SUCCESS = 'FETCH_ARTISTS_SUCCESS';
export const FETCH_ARTISTS_FAILURE = 'FETCH_ARTISTS_FAILURE';
export const SELECT_FAVORITE_ARTIST = 'SELECT_FAVORITE_ARTIST';
export const DESELECT_FAVORITE_ARTIST = 'DESELECT_FAVORITE_ARTIST';
export const REQUEST_FAVORITE_ARTISTS_START = 'REQUEST_FAVORITE_ARTISTS_START';
export const REQUEST_FAVORITE_ARTISTS_SUCCESS = 'REQUEST_FAVORITE_ARTISTS_SUCCESS';
export const REQUEST_FAVORITE_ARTISTS_FAILURE = 'REQUEST_FAVORITE_ARTISTS_FAILURE';

/* WAITING ACTIONS */
export const REQUEST_MAKE_GAME_START = 'REQUEST_MAKE_GAME_START';
export const REQUEST_MAKE_GAME_SUCCESS = 'REQUEST_MAKE_GAME_SUCCESS';
export const REQUEST_MAKE_GAME_FAILURE = 'REQUEST_MAKE_GAME_FAILURE';
export const FETCH_GAMES_START = 'FETCH_GAMES_START';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE';




